# Write a program to store seven fruits in a list entered by the user.
fruit1 = input("Enter fruit: ")
fruit2 = input("Enter fruit: ")
fruit3 = input("Enter fruit: ")
fruit4 = input("Enter fruit: ")
fruit5 = input("Enter fruit: ")
fruit6 = input("Enter fruit: ")
fruit7 = input("Enter fruit: ")
fruit_tuple = (fruit1, fruit2, fruit3, fruit4, fruit5, fruit6, fruit7)
print(fruit_tuple)